# Codecov Configuration
coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: 80%
        threshold: 2%
        base: auto
    patch:
      default:
        target: 80%
        threshold: 2%

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach, diff, flags, files, footer"
  behavior: default
  require_changes: false
  require_base: no
  require_head: yes

ignore:
  - "**/*.test.ts"
  - "**/*.test.tsx"
  - "**/*.spec.ts"
  - "**/*.spec.tsx"
  - "**/test-setup.ts"
  - "**/*.config.js"
  - "**/*.config.ts"
  - "**/next.config.js"
  - "**/.next/**"
  - "**/node_modules/**"
  - "**/coverage/**"
  - "**/playwright-report/**"
  - "**/*.d.ts"