blank_issues_enabled: false
contact_links:
  - name: 💬 General Discussion
    url: https://github.com/yourusername/netpost-v2/discussions
    about: Ask questions and discuss ideas with the community
  - name: 📖 Documentation
    url: https://github.com/yourusername/netpost-v2/wiki
    about: Read the project documentation and guides