# Deploy to Production (Vercel)
name: Deploy to Production

on:
  push:
    branches: [main]
    # Only trigger if web app or packages change
    paths:
      - 'apps/web/**'
      - 'packages/**'
      - 'package.json'
      - 'package-lock.json'
      - 'turbo.json'
      - 'vercel.json'

  # Allow manual deployment
  workflow_dispatch:
    inputs:
      force_deploy:
        description: 'Force deployment even if validation fails'
        required: false
        default: false
        type: boolean

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    permissions:
      contents: read
      deployments: write
      pull-requests: write

    steps:
      - name: 📦 Checkout code
        uses: actions/checkout@v4

      - name: 📋 Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '20'
          cache: 'npm'

      - name: 🔍 Run Enhanced Validation
        if: ${{ !inputs.force_deploy }}
        run: |
          npm ci
          npm run validate:enhanced
        env:
          NODE_ENV: production
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}

      - name: 🚀 Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: '--prod'
          scope: ${{ secrets.VERCEL_ORG_ID }}
          working-directory: ./

      - name: 💬 Comment on PR (if applicable)
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const deploymentUrl = process.env.VERCEL_URL || 'https://netpost-v2.vercel.app';

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `## 🚀 Deployment Successful!

              **Production URL**: ${deploymentUrl}

              ✅ Enhanced validation passed
              ✅ Deployed via Vercel
              ✅ All GitHub apps integrated

              The build cascade problem has been resolved! 🎉`
            });